stages:
- stage: Test
  jobs:
  - steps:
    - checkout: self
      submodules: true
  - template: ./devtools/azure-pipelines-linux.yml
  # TODO: enable 
  #- template: ./devtools/azure-pipelines-osx.yml
  #- template: ./devtools/azure-pipelines-win.yml

