version: 2

jobs:
  build:
    working_directory: ~/scikit-time/scikit-time
    docker:
    - image: continuumio/miniconda3
    parallelism: 1
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      PYTHONHASHSEED: 0
      OMP_NUM_THREADS: 2

    steps:
      - checkout
      - run: conda config --add channels conda-forge
      - run: conda config --set always_yes true
      - run: conda config --set quiet true
      - run: conda install conda-build -c defaults
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      - run: conda build devtools/conda-recipe --python=3.7
      - run: bash <(curl -s https://codecov.io/bash) -f $HOME/coverage.xml
      - store_test_results:
          path: /tmp/circleci-test-results
      # Save artifacts
      - store_artifacts:
          path: /tmp/circleci-artifacts
      - store_artifacts:
          path: /tmp/circleci-test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
