jobs:
- job:
  displayName: Win
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python37:
        CONDA_PY: '3.7'
        
  steps:
  - task: BatchScript@1
    filename: "$env:CONDA\\Scripts\\activate.bat" 
    displayName: Add conda to PATH
  - template: conda-setup+build.yml
