jobs:
- job:
  displayName: Win
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python37:
        CONDA_PY: '3.7'
        
  steps:
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH
  - template: conda-setup+build.yml
