steps:
  - bash: |
      conda config --add channels conda-forge
      conda config --set always_yes true
      conda config --set quiet true
      conda install conda-build conda-verify
    displayName: 'Install dependencies'
    continueOnError: false
  - bash: |
      conda build devtools
    displayName: 'Build and test'
    continueOnError: false
