package:
  name: scikit-time
  #version: dev+{{ GIT_DESCRIBE_TAG[1:] + '+' + GIT_DESCRIBE_NUMBER + '.' + GIT_DESCRIBE_HASH}}
  version: 0

source:
  path: ../..

build:
  script_env:
   - CIRCLE_TEST_REPORTS
   - OMP_NUM_THREADS
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp # [osx]
    - intel-openmp # [osx]

  host:
    - cython
    - intel-openmp # [osx]
    - mdtraj
    - numpy
    - python
    - scipy
    - setuptools
    - pip
    - pybind11

  run:
    - bhmm >=0.6.3,<0.7
    - intel-openmp # [osx]
    - msmtools >=1.2
    - {{ pin_compatible('numpy') }}
    - python
    - scipy
    - setuptools
    - tqdm

test:
  source_files:
    - tests/*
  requires:
    - scikit-learn

    - pytest
    - pytest-cov
    - pytest-faulthandler
    - pytest-xdist
    - pytest-sugar

